--- #YAML:1.0
name:                JSP
version:             1.01
abstract:            A bridge between JavaScript and Perl languages
license:             perl
author:              
    - Salvador Ortiz <sortiz@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Test::Exception:               0
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
